package net.dummy.web.vaadin;


import java.util.List;

import javax.inject.Inject;

import com.vaadin.annotations.Theme;
import com.vaadin.cdi.CDIUI;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.event.ItemClickEvent;
import com.vaadin.event.ItemClickEvent.ItemClickListener;
import com.vaadin.server.VaadinRequest;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Grid;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;

import net.dummy.dto.dummy.DummyDto;
import net.dummy.rest.client.dummy.DummyRestClient;


@Theme("valo")
@CDIUI("TestVaadin")
public class TestVaadin extends UI {
	
	private static final long serialVersionUID = 8329653938548335836L;
	
	@Inject
	private DummyRestClient dummyRestClient;
	
	private List<DummyDto> dummyDtoList;
	
	private TextField textName = null;
	private TextField textDescription = null;

	@Override
	protected void init(VaadinRequest request) {		
		VerticalLayout view = new VerticalLayout();
		setContent(view);
		
		/* Labels */
		/*for(DummyDto dummyDto : dummyRestClient.getList()) {
			view.addComponent(new Label(dummyDto.getName()));
		}*/
		
		/* Autogenerated form */
		/*FieldGroup fieldGroup = new BeanFieldGroup<DummyDto>(DummyDto.class);
		fieldGroup.setItemDataSource(new BeanItem<DummyDto>(dummyRestClient.getDummy(1L)));
		for (Object propertyId : fieldGroup.getUnboundPropertyIds()) {
            view.addComponent(fieldGroup.buildAndBind(propertyId));
        }*/
		
		/* Grid */
		Grid grid = new Grid();
		view.addComponent(grid);
		dummyDtoList = dummyRestClient.getList();
		BeanItemContainer<DummyDto> beanItemContainer = new BeanItemContainer<DummyDto>(DummyDto.class, dummyDtoList);
		grid.setContainerDataSource(beanItemContainer);
		grid.removeColumn("version");
		grid.setColumnOrder("id", "name", "description");
		grid.addItemClickListener(new ItemClickListener() {
			private static final long serialVersionUID = 503210947235841630L;

			@Override
			public void itemClick(ItemClickEvent event) {
				DummyDto dummyDto = (DummyDto)event.getItemId();
				textName.setValue(dummyDto.getName());
				textDescription.setValue(dummyDto.getDescription());
			}
		});
		
		/* Tab panel */
		TabSheet DummyTabSheet = new TabSheet();
		view.addComponent(DummyTabSheet);
		
		/* Tab 1 - Dummy info */
		VerticalLayout tab01 = new VerticalLayout();
		DummyTabSheet.addTab(tab01, "Dummy Info");
		textName = new TextField("Name");
		textDescription = new TextField("Description");
		tab01.addComponents(textName, textDescription);
		
		Button createButton = new Button("New Dummy");
		tab01.addComponent(createButton);
		createButton.addClickListener(new ClickListener() {
			private static final long serialVersionUID = 8946811161042614787L;
			
			@Override
			public void buttonClick(ClickEvent event) {
				DummyDto newDummyDto = new DummyDto();
				newDummyDto.setName(textName.getValue());
				newDummyDto.setDescription(textDescription.getValue());
				dummyRestClient.create(newDummyDto);
				
				beanItemContainer.removeAllItems();
				beanItemContainer.addAll(dummyRestClient.getList());
			}
		});
		
		/* Tab 2 - ? */
		VerticalLayout tab02 = new VerticalLayout();
		DummyTabSheet.addTab(tab02, "Tab 02");
		
	}
	
}
