package net.dummy.web.vaadin;


import javax.inject.Inject;

import net.dummy.dto.dummy.DummyDto;
import net.dummy.rest.client.dummy.DummyRestClient;

import com.vaadin.annotations.Theme;
import com.vaadin.cdi.CDIUI;
import com.vaadin.data.fieldgroup.BeanFieldGroup;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.data.util.BeanItem;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.server.VaadinRequest;
import com.vaadin.ui.Grid;
import com.vaadin.ui.Label;
import com.vaadin.ui.UI;
import com.vaadin.ui.VerticalLayout;


@Theme("valo")
@CDIUI("TestVaadin")
public class TestVaadin extends UI {
	
	private static final long serialVersionUID = 8329653938548335836L;
	
	@Inject
	private DummyRestClient dummyRestClient;

	@Override
	protected void init(VaadinRequest request) {
		VerticalLayout view = new VerticalLayout();
		setContent(view);
		
		/* Labels */
		for(DummyDto dummyDto : dummyRestClient.getList()) {
			view.addComponent(new Label(dummyDto.getName()));
		}
		
		/* Autogenerated form */
		FieldGroup fieldGroup = new BeanFieldGroup<DummyDto>(DummyDto.class);
		fieldGroup.setItemDataSource(new BeanItem<DummyDto>(dummyRestClient.getDummy(1L)));
		for (Object propertyId : fieldGroup.getUnboundPropertyIds()) {
            view.addComponent(fieldGroup.buildAndBind(propertyId));
        }
		
		
		/* Grid */
		Grid grid = new Grid();
		BeanItemContainer<DummyDto> beanItemContainer = new BeanItemContainer<DummyDto>(DummyDto.class, dummyRestClient.getList());
		grid.setContainerDataSource(beanItemContainer);
		grid.removeColumn("version");
		grid.setColumnOrder("id", "name", "description");
		view.addComponent(grid);
	}
	
}
